language: java

script: make

sudo: false

jdk:
  - oraclejdk8
#  - oraclejdk7
  - openjdk7

notifications:
  email:
    - mernst@cs.washington.edu

after_success:
  - bin/trigger-travis.sh codespecs daikon $TRAVISTOKEN
  - bin/trigger-travis.sh typetools plume-lib-typecheck $TRAVISTOKEN
