language: java

script: make

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

notifications:
  email:
    - mernst@cs.washington.edu

after-success:
  - bin/trigger-travis.sh mernst randoop JajuCi2u6gf8gABmQPAdxg
