language: java

script: make

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

notifications:
  email:
    - mernst@cs.washington.edu

after_success:
  - bin/trigger-travis.sh codespecs daikon $TRAVISTOKEN
