language: java

script: make

sudo: false

jdk:
  - oraclejdk8
#  - oraclejdk7
  - openjdk7

notifications:
  email:
    - mernst@cs.washington.edu

after_success:
  - curl -LO https://raw.github.com/mernst/plume-lib/master/bin/trigger-travis.sh
  - sh trigger-travis.sh codespecs daikon $TRAVISTOKEN "Triggered by upstream build of mernst/plume-lib"
  - sh trigger-travis.sh typetools plume-lib-typecheck $TRAVISTOKEN "Triggered by upstream build of mernst/plume-lib"
